pull_request_rules:
  - name: automatic merge when 2 reviews and we know the person
    conditions:
      - base=master
      - approved-reviews-by>=1
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - india
    conditions:
      - base=master
      - author=ajaytantry
      - files=india.md
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - test
    conditions:
      - base=master
      - author=test-noelelias
      - files=test.md
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - australia
    conditions:
      - base=master
      - author=Tutorialshubs
      - files=australia.md
    actions:
      merge:
        method: merge
  - name: automatic merge for technology representative of country - Germany
    conditions:
      - base=master
      - author=noelelias
      - files=germany.yml
    actions:
      merge:
        method: merge

